version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=production
      - DB_USERNAME=mahmoudhesham
      - DB_USERNAME_TEST=mahmoudhesham
      - DB_PASSWORD=nawytask
      - DB_PASSWORD_TEST=nawytask
      - DB_NAME=nawytask
      - DB_NAME_TEST=nawytask
      - DB_LOCAL_HOST=0.0.0.0
      - DB_LOCAL_PROTOCOL=mongodb://
      - CLIENT_URI=http://web:3000
      - SERVER_PORT=9999
      - SERVER_TOKEN_SECRET=hodasleemdubairaf
      - SERVER_TOKEN_EXPIRESIN=1d
      - SERVER_COOKIE_EXPIRESIN=7
      - SERVER_COOKIE_DOMAIN=localhost:3000
      - SERVER_CORS_ORIGIN=http://localhost:3000

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:9999

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge